Order lookup
softlayer/softlayer-python pull request #1354
Opened 2020-09-24 20:35 UTC by ATGE

2020-10-05 22:06 UTC, allmightyspiff commented
## TESTING
- ✔️ `slcli --format=table order lookup 66033262 --details`
- ✔️ `slcli --format=table order lookup 66033262`

2020-10-05 22:11 UTC, allmightyspiff requested changes
Looks good, thanks.

Also, can you update the docblock for `slcli account orders` to mention this new command.

From :
```
"""Order list account."""
```

To:
"""Lists recent orders. Use `slcli order lookup <ID>` to find more details about a specific order"""

or something like that.

2020-10-05 22:11 UTC, allmightyspiff commented on SoftLayer/CLI/order/lookup.py
> +    table.add_row(['status', order.get('status')])
Capitalize `Status`

2020-10-05 22:11 UTC, allmightyspiff commented on SoftLayer/CLI/order/lookup.py
> +    items = order.get('items', [])
Capitalize `Items`

2020-10-07 19:33 UTC, ATGE commented on SoftLayer/CLI/order/lookup.py
> +    table.add_row(['status', order.get('status')])
Done

2020-10-07 19:34 UTC, ATGE commented on SoftLayer/CLI/order/lookup.py
> +    items = order.get('items', [])
Done

2020-10-12 19:33 UTC, allmightyspiff approved these changes

2020-10-12 19:33 UTC, merged