Adding disaster recovery failover api method
softlayer/softlayer-python pull request #1407
Opened 2021-01-06 15:13 UTC by Rajarajan97

2021-01-06 20:24 UTC, allmightyspiff requested changes
Code looks good, only complaint is around some of the documentation bits. Should be a bit more clear that this is a sort of worst case scenario command to use.

2021-01-06 20:24 UTC, allmightyspiff commented on docs/cli/block.rst
> +
If there is any cloud.ibm.com/docs information on this feature, can you link it here?

Or at least elaborate a bit on some of the dangers of this command here.

2021-01-06 20:24 UTC, allmightyspiff commented on SoftLayer/CLI/block/replication/disaster_recovery_failover.py
> +    """Failover an inaccessible file volume to its available replicant volume."""
Might want to mention the dangers of running this command here. And maybe mention to use `replica-failover` for most cases?

2021-01-14 20:41 UTC, allmightyspiff approved these changes

2021-01-14 20:42 UTC, allmightyspiff commented
I will merge this when  FBLOCK-3769 is released.

2021-01-29 22:05 UTC, FernandoOjeda approved these changes
The code looks good.

2021-03-03 21:28 UTC, merged