add a flags in the report bandwidth
softlayer/softlayer-python pull request #1420
Opened 2021-02-12 22:20 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1419

2021-02-19 21:15 UTC, allmightyspiff requested changes
Need to refactor the Try/Except blocks, otherwise looks good, thanks.

2021-02-19 21:15 UTC, allmightyspiff commented on SoftLayer/CLI/report/bandwidth.py
> +    if virtual:
You should be using 1 Try/Except block here.

Something like this:


```python

try:
    if virtual:
        # get virtual bandwidth code
    elif hardware:
        # get hardware bandwidth code
    else:
        # do all 3 bandwidth things
except KeyboardInterrupt:
    env.err("Printing virtual collected results and then aborting.")



```

2021-02-19 21:49 UTC, ATGE approved these changes
looks good

2021-02-19 21:49 UTC, ATGE commented on SoftLayer/CLI/report/bandwidth.py
> +@click.option('--virtual', is_flag=True, help='show the all bandwidth summary virtual',
maybe  `'show the all bandwidth summary for each virtual server'`

2021-02-19 21:49 UTC, ATGE commented on SoftLayer/CLI/report/bandwidth.py
> +@click.option('--server', is_flag=True, help='show the all bandwidth summary bare metal',
maybe  `'show the all bandwidth summary for each hardware server'`

2021-02-24 20:59 UTC, ATGE approved these changes

2021-02-24 20:59 UTC, ATGE commented on SoftLayer/CLI/custom_types.py
> +# pylint: disable=inconsistent-return-statements
try to disable  in the method convert as:
`def convert(self, value, param, ctx):  # pylint: disable=R1710`

2021-02-24 20:59 UTC, ATGE commented on setup.py
> +# pylint: disable=inconsistent-return-statements
try to disable in the method `get_api_key` as:
`def get_api_key(client, username, secret):  # pylint: disable=R1710`

2021-02-26 20:49 UTC, allmightyspiff approved these changes
Looks good to me, thanks

2021-02-26 20:49 UTC, merged