Add preset datatype in `slcli virtual detail`
softlayer/softlayer-python pull request #1435
Opened 2021-03-09 19:37 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1434

2021-03-11 14:54 UTC, FernandoOjeda approved these changes
LGTM.

2021-03-12 20:47 UTC, allmightyspiff commented on SoftLayer/CLI/virt/detail.py
> +    table.add_row(['preset', result['billingItem']['orderItem']['preset']['keyName']])
for deep lookups like this, `utils.lookup` would be my recommendation.

`utils.lookup(result, 'billintItem', 'orderItem', 'preset', 'keyName')`

2021-03-12 20:48 UTC, allmightyspiff requested changes
Use `utils.lookup` to avoid keyErrors when adding in a preset.

2021-03-15 23:32 UTC, ATGE requested changes

2021-03-15 23:32 UTC, ATGE commented on SoftLayer/CLI/virt/detail.py
> +                                          'keyName') or {}])
Use `-` as default to avoid printing a preset as `preset : {}  `
```suggestion
                                          'keyName') or '-'])
```

2021-03-16 20:14 UTC, ATGE approved these changes
### Testing 

- ✔️ slcli vs detail 107879710
- ✔️ slcli vs detail 112238162

2021-03-19 18:19 UTC, merged

2021-03-19 18:20 UTC, allmightyspiff reviewed
approved