Show component versions on hw detail
softlayer/softlayer-python pull request #1470
Opened 2021-04-16 22:45 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1465

2021-04-16 23:43 UTC, ATGE commented on SoftLayer/CLI/hardware/detail.py
> +        _mask = 'id,hardwareComponentModel[name,' \
moving `_mask` and `_filter` logic within the `getcomponents` , will look better.

2021-04-16 23:43 UTC, ATGE commented on SoftLayer/CLI/hardware/detail.py
> +        components = hardware.get_components(identifier, _mask, _filter)
```suggestion
        components = hardware.get_components(identifier)
```
after moving `_mask` and `_filter` within `get_components(identifier)`

2021-04-16 23:43 UTC, ATGE commented on tests/managers/hardware_tests.py
> +
```suggestion
self.assert_called_with('SoftLayer_Hardware_Server',
                                'getComponents',
                                identifier=1234)
```
testing the API calls helps to sure they will work as expected too.

2021-04-21 00:20 UTC, ATGE reviewed
### Testing
- ✔️ slcli hw detail --components 1866407 
```bash
:       components : :.....................:................:...........................:..................:                         :
:                  : :         name        :    version     : date                      :  component-type  :                         :
:                  : :.....................:................:...........................:..................:                         :
:                  : :    X11DPU+_R1.10    : 3.3a 7-21-2020 : 2020-08-28T12:48:59-06:00 :   MOTHERBOARD    :                         :
:                  : :   AOC-2UR66-i4XTF   :   6.01(6.01)   : 2021-02-16T11:46:32-06:00 :   NETWORK_CARD   :                         :
:                  : :       9461-16i      : 5.130.00-3059  : 2020-05-22T10:44:07-06:00 : DRIVE_CONTROLLER :                         :
:                  : :  AST2500 - Onboard  :      3.10      : 2020-09-16T15:09:26-06:00 : REMOTE_MGMT_CARD :                         :
:                  : :    AOM-TPM-9671H    :   6.43.243.0   : 2020-01-24T15:28:41-06:00 : SECURITY_DEVICE  :                         :
:                  : : Enterprise Capacity :   TN04 TN04    : 2019-07-09T20:58:53-06:00 :    HARD_DRIVE    :                         :
:                  : : Enterprise Capacity :   TN04 TN04    : 2019-07-09T20:58:53-06:00 :    HARD_DRIVE    :                         :
:                  : :.....................:................:...........................:..................:                         :
:             tags : -                                                                                                               :
:..................:.................................................................................................................:
```
below, some suggestions to improve the information about the components(maybe adding the id too)::

```
:       components : :...............................................................................:..................:...........................:..................: :
:                  : :                                      name                                     : Firmware version :    Firmware build date    :       Type       : :
:                  : :...............................................................................:..................:...........................:..................: :
:                  : :       SuperMicro / MBD-X11DPU / X11DPU+_R1.10 / Intel Xeon DualProc / 2       :  3.3a 7-21-2020  : 2020-08-28T12:48:59-06:00 :   MOTHERBOARD    : :
:                  : :             SuperMicro / AOC-2UR66-I4XTF / AOC-2UR66-i4XTF / 1 / 4            :    6.01(6.01)    : 2021-02-16T11:46:32-06:00 :   NETWORK_CARD   : :
:                  : : LSI / DRIVE CONTROLLER / 9461-16i / SATA/SAS - MegaRAID SAS 9461-16i SGL / 16 :  5.130.00-3059   : 2020-05-22T10:44:07-06:00 : DRIVE_CONTROLLER : :
:                  : :       Aspeed / AST2500 - Onboard / IPMI - KVM / Remote Management Count1      :       3.10       : 2020-09-16T15:09:26-06:00 : REMOTE_MGMT_CARD : :
:                  : :     SuperMicro / AOM-TPM-9671H-P / AOM-TPM-9671H / Infineon TPM Module / 1    :    6.43.243.0    : 2020-01-24T15:28:41-06:00 : SECURITY_DEVICE  : :
:                  : :       Seagate / ST1000NM0055 / Enterprise Capacity / ST1000NM0055 / 1000      :    TN04 TN04     : 2019-07-09T20:58:53-06:00 :    HARD_DRIVE    : :
:                  : :       Seagate / ST1000NM0055 / Enterprise Capacity / ST1000NM0055 / 1000      :    TN04 TN04     : 2019-07-09T20:58:53-06:00 :    HARD_DRIVE    : :
:                  : :...............................................................................:..................:...........................:..................: :
:             tags : -                                                                                                                                                   :
:..................:.....................................................................................................................................................:

```

2021-04-21 00:20 UTC, ATGE commented on SoftLayer/CLI/hardware/detail.py
> +        components_table = formatting.Table(['name', 'version', 'date', 'component-type'])
```suggestion
                components_table = formatting.Table(['name', 'Firmware version', 'Firmware build date', 'Type'])
```
maybe adding the id too

2021-04-21 00:20 UTC, ATGE commented on SoftLayer/CLI/hardware/detail.py
> +                components_table.add_row([utils.lookup(component, 'hardwareComponentModel', 'name'),
```suggestion
               components_table.add_row([utils.lookup(component, 'hardwareComponentModel', 'longDescription'),
```

2021-04-21 22:24 UTC, allmightyspiff requested changes
Looks good. I like @atge 's suggestions, once those are added this should be good to go.

Thanks.

2021-04-21 22:24 UTC, allmightyspiff commented on SoftLayer/CLI/hardware/detail.py
> +@click.option('--components', is_flag=True, help='Show associated hardware components')
Set the default to false

2021-04-21 22:24 UTC, allmightyspiff commented on SoftLayer/CLI/hardware/detail.py
> +            if component['id'] not in ids:
Are there duplicate `ids` in the components list? I would assume this check wouldn't be needed. But if this check is preventing duplicate line entries or something feel free to keep it in there.

2021-04-29 19:38 UTC, allmightyspiff requested changes
Looks good, but there are some unintended changes here. Please update this branch with the latest changes from master and I think those should go away, hopefully.

Once that is done this should be good to go. Thanks.

2021-05-05 18:21 UTC, allmightyspiff commented
Thanks for merging in the changes from master, but it still looks like your accidently committing changes you didn't mean to.
Take a look at https://github.com/softlayer/softlayer-python/pull/1470/files and make sure ONLY the changes you intent to make are in there.

2021-05-14 18:31 UTC, allmightyspiff approved these changes

2021-05-14 18:32 UTC, merged