add new email feature
softlayer/softlayer-python pull request #1483
Opened 2021-05-05 13:55 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1482

2021-05-05 18:45 UTC, allmightyspiff requested changes
A good start, thanks.

- Change the CLI path to be `slcli email list` since this function lists out all accounts.
- Update some of the function names to match the style of the rest of the slcli
- Make the Stats/Overview tables into long column tables, not key value tables to look more compact
- your `get_statistics` method should set some default values if none were supplied.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/CLI/email/detail.py
> +"""Get details for an image."""
Fix this to match the `cli` docblock comment.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/CLI/email/detail.py
> +    """Display the Email Delivery account informatino """
Should be: `Lists Email Delivery Service `

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/CLI/email/detail.py
> +def _build_overview_table(email_overview):
Instead of using a KeyValueTable here, try a normal table with columns instead of rows. I think that would end up looking nicer as output.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/CLI/email/detail.py
> +def _build_statistics_table(statistics):
Instead of using a KeyValueTable here, try a normal table with columns instead of rows. I think that would end up looking nicer as output.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/CLI/routes.py
> +    ('email:detail', 'SoftLayer.CLI.email.detail:cli'),
I think the command should be called `email:list` since it lists all the accounts, and not one specific account.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/managers/account.py
> +    def get_Network_Message_Delivery_Accounts(self):
function should be called `get_network_message_delivery_accounts`

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/managers/email.py
> +    def get_AccountOverview(self, identifier):
function should be called `get_account_overview`

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/managers/email.py
> +        body = [selectedStatistics,
except for `identifier` the user shouldn't have to know/provide all these details. This manager function should set some defaults if the values are not provided.

2021-05-05 18:45 UTC, allmightyspiff commented on SoftLayer/managers/email.py
> +        """Gets statistics Network Message Delivery Account
This docblock should explain what all these parameters are meant to do, and what some valid values of them are.

2021-05-05 21:22 UTC, FernandoOjeda commented on SoftLayer/CLI/email/detail.py
> +                                                  True, True, True, 6)
If these data are by default (**["requests", "delivered", "opens", "clicks", "bounds"], True, True, True, 6**) you do not need to send them as parameters, use them direct in the method. Send only the email id:

`statistics = email_manager.get_statistics(email.get('id'))`

2021-05-07 23:29 UTC, ATGE commented on tests/managers/email_tests.py
> +        self.manager = EmailManager(self.client)
move  `self.manager = EmailManager(self.client)` to setup
```suggestion
       
```

2021-05-07 23:29 UTC, ATGE commented on tests/managers/email_tests.py
> +
```suggestion
def set_up(self):
        self.manager = EmailManager(self.client)
```

2021-05-07 23:29 UTC, ATGE commented on tests/managers/email_tests.py
> +        self.assert_called_with('SoftLayer_Network_Message_Delivery_Email_Sendgrid',
args=expected_args)
```suggestion
        self.assert_called_with('SoftLayer_Network_Message_Delivery_Email_Sendgrid',
        'getStatistics',
         , identifier=1232123,
         args=expected_args)
```

2021-05-07 23:29 UTC, ATGE commented on SoftLayer/managers/email.py
> +                                'getStatistics', id=identifier, *body)
```suggestion
                                'getStatistics', id=identifier, body)
```
I'm not sure if a `*` is needed here, I think just the args itself is enough.

2021-05-14 15:33 UTC, ATGE reviewed
### Testing
 - ✔️slcli email -h
- ✔️slcli email list
 Looks good, 
```bash
$ slcli -h | grep email
  email
```
 just shows the command email, adds a description and will look better.
something like:
```bash
$ slcli -h | grep email
  email Manage Email Delivery Service
```

you can add the descriptioon by adding:
"""Manage Email Delivery Service.""" in the `SoftLayer/CLI/email/__init__.py` file

- add email in `docs/cli.rst` too

2021-05-24 19:29 UTC, allmightyspiff requested changes
Fix the docblock in email/list.py and @ATGE's comments, and this should be good to go.

Thanks.

2021-05-24 19:29 UTC, allmightyspiff commented on SoftLayer/CLI/email/list.py
> +"""Get lists Email Delivery account Service """
```suggestion
"""Lists Email Delivery Service """
```

2021-06-03 16:08 UTC, allmightyspiff approved these changes

2021-06-03 16:08 UTC, merged