Add gateway/firewall name to vlan detail and list command
softlayer/softlayer-python pull request #1498
Opened 2021-06-02 20:36 UTC by ATGE

fixes #1480

2021-06-02 20:44 UTC, ATGE commented
### Testing 

- ✔️slcli vlan detail 2282897 | grep Gateway
      Gateway/Firewall  support    
                                                        
- ✔️ slcli vlan detail 361652 | grep Firewall
      Gateway/Firewall  firewall-vlan.networklayer.com  

- ✔️$slcli vlan list

2021-06-03 16:31 UTC, allmightyspiff approved these changes
Looks good, thanks

2021-06-04 21:43 UTC, caberos approved these changes
LGTM.

2021-06-09 20:47 UTC, FernandoOjeda reviewed
Looks good, just check my comment on the network manager.

2021-06-15 21:27 UTC, allmightyspiff requested changes

2021-06-15 21:27 UTC, allmightyspiff commented on SoftLayer/managers/network.py
> +    def get_network_gateway_firewall(self, vlan_id):
I think this method could just be removed entirely, it doesn't look like its actually called anywhere to me. And if it is called somewhere, please replace it with `get_vlan` as Fernando suggested. Thanks

2021-06-18 01:34 UTC, ATGE reviewed
### TESTED:
✔️slcli vlan detail 2282897 | grep Gateway
Gateway/Firewall support

✔️ slcli vlan detail 361652 | grep Firewall
Gateway/Firewall firewall-vlan.networklayer.com

✔️$slcli vlan list

2021-06-18 01:37 UTC, ATGE commented on SoftLayer/managers/network.py
> +    def get_network_gateway_firewall(self, vlan_id):
`get_network_gateway_firewall` was removed 👍

2021-06-21 15:55 UTC, allmightyspiff approved these changes

2021-06-21 15:55 UTC, merged