Refactor loadbal order-options
softlayer/softlayer-python pull request #1521
Opened 2021-07-26 21:53 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1520

2021-07-30 00:09 UTC, ATGE reviewed
the command `slcli lb order-options` works well, just the message displayed as an error looks weird.
Also, the output of the `slcli lb order-options --datacenter <DC>` in the worked branch is the same output as the latest `slcli` version shows, so looks like the table requirement mentioned in the issue, is not implemented. #1520 

> `slcli lb order-options -d dal10` works fine, but should output 2 tables, instead of 1 table with a table in each column.
> 
> Table 1 titled " Prices", Table 2 titled " Subnets Private Subnets"
### Testing
 - ✔️ slcli loadbal order-options
 
 
![image](https://user-images.githubusercontent.com/30413337/127579491-a4e01ef2-51e7-4366-b321-97379b305e1a.png)

- slcli loadbal order-options -d dal13
 worked branch output:
![image](https://user-images.githubusercontent.com/30413337/127579621-b66d015a-2828-475c-8acd-92e839adf6b2.png)
 slcli (SoftLayer Command-line) v5.9.6 output:
![image](https://user-images.githubusercontent.com/30413337/127579931-bced0bf4-a04a-41a1-8273-b1fb1f8c3bfd.png)

2021-08-02 21:19 UTC, allmightyspiff requested changes
Along with my comments, I'd like to see a unit test specifically for this command with a location specified.

2021-08-02 21:19 UTC, allmightyspiff commented on SoftLayer/CLI/loadbal/order.py
> +    else:
Most of this logic is just table formatting, so I'm ok with it not being in a manager specifically, unless we want to use it in more than just this one command. Breaking it up into a few smaller sub-functions that return `Table` objects would make this logic a bit more readable though.

2021-08-02 21:19 UTC, allmightyspiff commented on SoftLayer/CLI/loadbal/order.py
> +            env.fout(this_table)
I'd like this to be 2 tables now, so the following should produce the output I'm looking for.

```suggestion
            env.fout(price_table)
            env.fout(subnet_table)
```

2021-08-03 20:52 UTC, allmightyspiff requested changes
Make sure to lowercase user input for datacenter here. Otherwise this looks great and ready to merge. Thanks.

2021-08-03 20:52 UTC, allmightyspiff commented on SoftLayer/CLI/loadbal/order.py
> +            if datacenter and dc_name != datacenter:
The datacenter lists the DC name as all uppercase (`DAL13`), but if you search for `DAL13`, this command fails to find the right DC (as opposed to `dal13`)

Need to lowercase the input so it matches what we get from the API.

```suggestion
            if datacenter and dc_name != datacenter.lower():
```

![image](https://user-images.githubusercontent.com/7408017/128084413-7fa5ae3b-71b2-46b0-9bcb-162ed4e565a6.png)

2021-08-04 20:50 UTC, allmightyspiff approved these changes
Thanks, changes look good.

2021-08-04 20:50 UTC, merged