Add an orderBy filter to slcli vlan list
softlayer/softlayer-python pull request #1599
Opened 2022-03-23 16:09 UTC by caberos

https://github.com/softlayer/softlayer-python/issues/1598

2022-03-23 22:17 UTC, edsonarios commented
Screenshots of the result 
![image](https://user-images.githubusercontent.com/43519769/159805278-414e20cc-3081-4a11-b1f0-6069a498513a.png)

2022-03-23 22:17 UTC, edsonarios approved these changes
Looks good to me

2022-03-24 19:27 UTC, allmightyspiff requested changes
The only problem I have with this change is that it changes the default behavior of `list_vlans` from  "Get all vlans in pages of 100" to "Get only 100 vlans", which I think will cause issues with some customers who have a lot of vlans.

I think we should default `limit` to `None` in the function definition and in the CLI argument list. So that if the user doesn't set a limit, they get all vlans back.
If a user does set a limit, they only get that number back.

Something like this:
```python
 if limit > 0:
    return self.account.getNetworkVlans(mask=kwargs['mask'], filter=_filter.to_dict(), limit=limit)
else:
    self.account.getNetworkVlans(mask=kwargs['mask'], filter=_filter.to_dict(), iter=True)

```

2022-04-07 23:04 UTC, allmightyspiff approved these changes

2022-04-07 23:04 UTC, merged