update the firewall list
softlayer/softlayer-python pull request #1649
Opened 2022-05-24 15:11 UTC by caberos

[#issue1643](https://github.com/softlayer/softlayer-python/issues/1643)

![image](https://user-images.githubusercontent.com/22535437/170070145-cedda059-ed73-4be5-a466-7b7624c235d5.png)

2022-05-25 20:54 UTC, BrianSantivanez commented on SoftLayer/CLI/firewall/list.py
> +        table_gatewalls.add_row([gatewalls.get('id'), gatewalls.get('name'),
Display the ID with the format `multiVlan:FIREWALL_ID`, where `multiVlan` is constant and `FIREWALL_ID` is the firewall id

2022-05-26 17:10 UTC, allmightyspiff requested changes
Looks good, just a minor doc change needed please.

Thanks

2022-05-26 17:10 UTC, allmightyspiff commented on SoftLayer/managers/firewall.py
> +        """
I dont mean to nit-pick here, but `gatewall` isn't an English word. However as a mashup of "gateway" + "firewall" I do kinda like it, and want to keep it. Just make the following change to the docblock so anyone else knows you put `gatewalls` on purpose, and just didn't misspell `gateways`, which is what I thought when I first saw it lol.

```suggestion
    def get_firewalls_gatewalls(self):
        """Returns a list of all gateway firewalls (gatewalls) on the account.

        returns: A list of gateway firewalls (gatewalls) on the current account.
        """
```

2022-05-31 14:29 UTC, allmightyspiff approved these changes

2022-05-31 14:29 UTC, merged