New command ipsec order
softlayer/softlayer-python pull request #1698
Opened 2022-07-18 14:00 UTC by caberos

[#issue1696](https://github.com/softlayer/softlayer-python/issues/1696)

![image](https://user-images.githubusercontent.com/22535437/179528291-9a56e08a-7190-4050-bda0-650ab99c1ca9.png)

2022-07-19 14:48 UTC, BrianSantivanez commented on SoftLayer/CLI/vpn/ipsec/order.py
> +    result = ipsec_manager.order(datacenter, ['IPSEC_STANDARD'])
Like ipsec has a cost, I think it is a good idea to add a confirmation before to order
```
        if not (env.skip_confirmations or formatting.confirm(
                "This action will incur charges on your account. Continue?")):
            raise exceptions.CLIAbort('Aborting ipsec order.')
```

2022-07-19 15:36 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/179790823-9efa3727-6d5c-4b93-bbd8-674252e330f2.png)
![image](https://user-images.githubusercontent.com/43519769/179790909-426bb58a-5bc6-498e-8d99-7c8942b5eed2.png)

2022-07-21 15:32 UTC, allmightyspiff requested changes
Looks good, just need a unit test for the new manager function you added, and a confirmation for the order like Brian mentioned. Thanks

2022-07-21 15:32 UTC, allmightyspiff commented on SoftLayer/managers/ipsec.py
> +    def order(self, datacenter, item_package):
Add a unit test for this new function

2022-07-29 20:30 UTC, allmightyspiff approved these changes

2022-07-29 20:30 UTC, merged