Command slcli vlan create - displaying an error message
softlayer/softlayer-python pull request #1707
Opened 2022-07-25 16:40 UTC by edsonarios

Issue link: #1706 
```
softlayer-python/ (issue1706 *) $ slcli vlan create -h
Usage: slcli vlan create [OPTIONS]

        Order/create a VLAN instance.

Example:
    slcli vlan create --name myvlan --datacenter dal13
    or
    slcli vlan create --name myvlan --pod dal10.pod01

┌────┬──────────────┬──────────────────────────────────────┐
│    │ --name       │ Vlan name                            │
│ -d │ --datacenter │ Datacenter shortname                 │
│ -p │ --pod        │ Pod name. E.g dal05.pod01            │
│    │ --network    │ Network vlan type  [default: public] │
│    │ --billing    │ Billing rate  [default: hourly]      │
│ -h │ --help       │ Show this message and exit.          │
└────┴──────────────┴──────────────────────────────────────┘
```

2022-07-26 12:36 UTC, caberos approved these changes
LGTM

2022-07-29 20:48 UTC, allmightyspiff requested changes

2022-07-29 20:48 UTC, allmightyspiff commented on SoftLayer/CLI/vlan/create.py
> +        raise exceptions.CLIAbort("Is required Datacenter or Pod")
```suggestion
        raise exceptions.CLIAbort("--datacenter or --pod is required to create a VLAN")
```

2022-07-29 20:49 UTC, allmightyspiff approved these changes

2022-07-29 21:02 UTC, merged