add new command on ipsec cancel command
softlayer/softlayer-python pull request #1729
Opened 2022-08-12 14:16 UTC by caberos

[#issue1725](https://github.com/softlayer/softlayer-python/issues/1725)

slcli ipsec cancel 3892 --immediate --reason test --comment testcli

![image](https://user-images.githubusercontent.com/22535437/184372232-ee760255-2ee9-4b9d-9fef-dd28cfc0789d.png)

2022-08-12 18:20 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/184412868-3c01bd3a-28b0-4b51-8320-2507f218bad9.png)

In this case, if I send the same id that was cancelled, display a message of the crash code
![image](https://user-images.githubusercontent.com/43519769/184412979-5dc0a2df-c95a-4c9f-9cf2-f1f5a35d65f5.png)

2022-08-17 21:52 UTC, allmightyspiff requested changes
A few minor changes needed, thanks.

2022-08-17 21:52 UTC, allmightyspiff commented on SoftLayer/CLI/vpn/ipsec/cancel.py
> +    result = manager.cancel_item(context['billingItem']['id'], immediate, reason, comment)
Edson mentioned this in his review, but you need to check for a billingItem first. 

```python
        if 'billingItem' not in context:
            raise SoftLayerError("Cannot locate billing. May already be cancelled.")
```

2022-08-17 21:52 UTC, allmightyspiff commented on SoftLayer/CLI/vpn/ipsec/cancel.py
> +"""Cancel a dedicated server."""
```suggestion
"""Cancel an IPSec service."""
```

2022-08-17 21:52 UTC, allmightyspiff commented on SoftLayer/CLI/vpn/ipsec/cancel.py
> +              help="Cancels the server immediately (instead of on the billing anniversary)")
```suggestion
              help="Cancels the service immediately (instead of on the billing anniversary)")
```

2022-08-17 21:52 UTC, allmightyspiff commented on SoftLayer/CLI/vpn/ipsec/cancel.py
> +              help="An optional comment to add to the cancellation ticket")
I dont think we really need these options. If we need to send them into the API, just set them to something generic in the `manager.cancel_item` function.

2022-08-30 21:02 UTC, allmightyspiff approved these changes

2022-08-30 21:02 UTC, merged