add vs user-access command
softlayer/softlayer-python pull request #1741
Opened 2022-08-29 20:20 UTC by caberos

[#ussue1739](https://github.com/softlayer/softlayer-python/issues/1739)

![image](https://user-images.githubusercontent.com/22535437/187290897-c78a4f6e-f375-4cfe-8a99-d6579938bc23.png)

2022-08-30 21:18 UTC, allmightyspiff requested changes
Looks good, just change the username in the fixtrues, and the first line comment of the new command.

2022-08-30 21:18 UTC, allmightyspiff commented on SoftLayer/CLI/virt/access.py
> +"""Command lines which modify power states."""
```suggestion
"""Get user access details a virtual server.""
```

2022-08-30 21:18 UTC, allmightyspiff commented on SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
> +        "username": "307608_sebastian.chaparro@ibm.com"
Dont put real emails/usernames in the fixtures, compliance doens't like that.
```suggestion
        "username": "testuser@ibm.com"
```

2022-08-30 21:18 UTC, allmightyspiff commented on SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
> +        "username": "307608_sebastian.chaparro@ibm.com"
```suggestion
        "username": "testuser@ibm.com"
```

2022-08-31 15:09 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/187713459-02c7bb09-bcf9-4e27-af13-e5e9df38457f.png)

2022-09-08 18:46 UTC, allmightyspiff approved these changes

2022-09-08 18:46 UTC, merged