new command hw create-credential
softlayer/softlayer-python pull request #1774
Opened 2022-10-21 15:08 UTC by caberos

[#issue1677](https://github.com/softlayer/softlayer-python/issues/1773)

![image](https://user-images.githubusercontent.com/22535437/197228453-af6db9c8-edb2-4a5b-998e-da503da6d516.png)

2022-10-21 18:34 UTC, allmightyspiff requested changes

2022-10-21 18:34 UTC, allmightyspiff commented on SoftLayer/CLI/hardware/create_credential.py
> +                sw_id = sw_instance['id']
I dont understand what you are checking for here?

Looks to me like you are checking for if a user picked `--system`, but then you just set sw_id to `Passmark Suite`. I feel like this whole `elif` check could be removed, and if at the end if your for loop, if `sw_id` is None and `system` is not None, throw and exception about not being able to find a software called `system`

2022-10-21 18:34 UTC, allmightyspiff commented on SoftLayer/managers/hardware.py
> +        """Returns Hardware sensor data"""
Fix this doc line to reflect what this function actually does.

2022-10-21 18:34 UTC, allmightyspiff commented on SoftLayer/CLI/hardware/create_credential.py
> +@click.option('--system', help="The name of this specific piece of software.")
If these are required, you should mark them as such, and if not, set a default value.

2022-10-24 22:29 UTC, edsonarios approved these changes
Looks good to me

2022-10-26 23:00 UTC, allmightyspiff approved these changes

2022-10-26 23:00 UTC, merged