Improve subnet detail
softlayer/softlayer-python pull request #1803
Opened 2022-12-06 19:36 UTC by caberos

[#issue1799](https://github.com/softlayer/softlayer-python/issues/1799)

![image](https://user-images.githubusercontent.com/22535437/206005787-c956b8b3-fa08-4634-8548-df2d65d4c25e.png)

2022-12-06 21:58 UTC, allmightyspiff requested changes

2022-12-06 21:58 UTC, allmightyspiff commented on SoftLayer/CLI/subnet/detail.py
> +                          subnet['networkVlan']['primaryRouter']['fullyQualifiedDomainName'], address.get('note')])
I want the `hardware` or `virtualGuest` fullyQualifiedDomainName added here, not the primaryRouter name

2022-12-16 13:28 UTC, allmightyspiff approved these changes

2022-12-16 14:00 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/208114335-07455e48-4bdb-4010-b6f5-3713494901bc.png)

2022-12-16 14:00 UTC, edsonarios approved these changes
Looks good to me

2023-01-03 21:03 UTC, merged