Improve subnet list
softlayer/softlayer-python pull request #1805
Opened 2022-12-07 21:20 UTC by edsonarios

Issue link #1798
![image](https://user-images.githubusercontent.com/43519769/206298706-e333c5e2-f241-4646-a125-0009e92a4559.png)

2022-12-07 22:11 UTC, caberos requested changes

2022-12-09 19:17 UTC, BrianSantivanez commented on SoftLayer/CLI/subnet/list.py
>              len(subnet['virtualGuests']),
Maybe like hardware and virtual guest counters are not displayed on IBM portal, they could be removed

2022-12-12 13:17 UTC, edsonarios commented
> `stop`

I don't understand with your comment, please you can specify it

2022-12-12 13:41 UTC, edsonarios commented on SoftLayer/CLI/subnet/list.py
> +            subnet_type = 'Primary'
I take the UI like example for to make it look similar, I think it's better like this

2022-12-12 14:09 UTC, allmightyspiff approved these changes

2022-12-15 23:24 UTC, merged