`user remove-access` is not displaying all removed device access and its help command displaying error message
softlayer/softlayer-python pull request #1824
Opened 2023-01-11 15:27 UTC by BrianSantivanez

Issue: https://github.com/softlayer/softlayer-python/issues/1823
Observations: The command was updated to print an message of each removed device access, the short flags were removed to can use short help flag and the help flags were updated to match with golang plugin
```
slcli user remove-access 8344222 --hardware 1532729 --virtual 132364928
Remove to access to hardware: 1532729
Remove to access to virtual guest: 132364928
```
```
slcli user remove-access -h
Usage: slcli user remove-access [OPTIONS] IDENTIFIER

        Remove access from a user to an specific device.

Example: slcli user remove-access 123456 --hardware 123456789

┌────┬─────────────┬─────────────────────────────┐
│    │ identifier  │                             │
│    │ --hardware  │ Hardware ID                 │
│    │ --virtual   │ Virtual Guest ID            │
│    │ --dedicated │ Dedicated host ID           │
│ -h │ --help      │ Show this message and exit. │
└────┴─────────────┴─────────────────────────────┘
```

2023-01-16 21:01 UTC, allmightyspiff requested changes
looks good, just convert to `f` strings. Thanks

2023-01-16 21:01 UTC, allmightyspiff commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to hardware: %s" % hardware, fg='green')
```suggestion
            click.secho(f"Removed access to hardware: {hardware}.", fg='green')
```

2023-01-16 21:01 UTC, allmightyspiff commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to virtual guest: %s" % virtual, fg='green')
```suggestion
            click.secho(f"Removed access to virtual guest: {virtual}", fg='green')
```

2023-01-16 21:01 UTC, allmightyspiff commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to dedicated host: %s" % dedicated, fg='green')
```suggestion
            click.secho("Removed access to dedicated host: {dedicated}", fg='green')
```

2023-01-17 14:53 UTC, BrianSantivanez commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to dedicated host: %s" % dedicated, fg='green')
Done

2023-01-17 14:55 UTC, BrianSantivanez commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to virtual guest: %s" % virtual, fg='green')
Done

2023-01-17 14:55 UTC, BrianSantivanez commented on SoftLayer/CLI/user/remove_access.py
> +            click.secho("Remove to access to hardware: %s" % hardware, fg='green')
Done

2023-01-18 14:50 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/213202788-a18a5cf0-5e10-45de-b88d-60b14ee508f8.png)

2023-01-18 14:50 UTC, edsonarios approved these changes
Looks good to me

2023-01-20 23:11 UTC, allmightyspiff approved these changes

2023-01-20 23:11 UTC, merged