unexpected error when using vlan list with --limit 0 or 999 and a lar…
softlayer/softlayer-python pull request #1847
Opened 2023-01-27 22:24 UTC by caberos

[#issue1844](https://github.com/softlayer/softlayer-python/issues/1844)

![image](https://user-images.githubusercontent.com/22535437/215217441-1844f9b9-bb70-4e4b-91a6-e78e4d0bdaab.png)

2023-01-30 13:39 UTC, edsonarios approved these changes
Looks good to me

2023-01-30 15:56 UTC, allmightyspiff requested changes
Change the default response for a null `networkSpace` to `Direct Link`
Add a unit test for getting a vlan with an empty networkSpace property as well.

Thanks

2023-01-30 15:56 UTC, allmightyspiff commented on SoftLayer/CLI/vlan/list.py
> +            vlan.get('networkSpace').capitalize() or formatting.blank(),
Apparently Vlans with a null `networkSpace` are Direct Link vlans, so lets label them as such.

```suggestion
            vlan.get('networkSpace', 'DIRECT LINK').capitalize() ,
```

Also, I think `vlan.get('networkSpace').capitalize() or formatting.blank()` will still error on an empty `networkSpace` property. Setting a default for `vlan.get` should fix that.

2023-02-01 02:59 UTC, allmightyspiff approved these changes

2023-02-01 02:59 UTC, merged