slcli vlan list only returns 100 results
softlayer/softlayer-python pull request #1852
Opened 2023-02-03 21:40 UTC by caberos

[#issue1851](https://github.com/softlayer/softlayer-python/issues/1851)

![image](https://user-images.githubusercontent.com/22535437/216715967-d7a30494-32f1-4d5f-9c53-2e4d01b52e53.png)

2023-02-03 22:23 UTC, allmightyspiff requested changes
The purpose of this issue is to make sure `slcli vlan list` ALWAYS prints all vlans.

2023-02-03 22:23 UTC, allmightyspiff commented on SoftLayer/managers/network.py
> +            return self.account.getNetworkVlans(mask=kwargs['mask'], filter=_filter.to_dict(), limit=limit, iter=False)
```suggestion
            return self.account.getNetworkVlans(mask=kwargs['mask'], filter=_filter.to_dict(), limit=limit, iter=True)
```

2023-02-06 12:51 UTC, edsonarios commented
Screenshot of the test result
![image](https://user-images.githubusercontent.com/43519769/216975976-c08ea75f-2222-451e-8e69-5eccb037be31.png)

2023-02-06 12:52 UTC, edsonarios approved these changes
Apart from the comment, looks good to me

2023-02-07 14:46 UTC, merged