New command `slcli image share`
softlayer/softlayer-python pull request #1861
Opened 2023-03-01 17:27 UTC by edsonarios

Issue: #1853
```
softlayer-python/ (issue1853) $ slcli image share 57065 --account-id 1234
Image template 57065 was shared to account 1234.
```

2023-03-06 15:25 UTC, BrianSantivanez commented on SoftLayer/CLI/image/share.py
> +"""Get details for an image."""
Update this comment

2023-03-09 12:56 UTC, edsonarios commented on SoftLayer/CLI/image/share.py
> +"""Get details for an image."""
Done

2023-03-10 22:00 UTC, caberos commented
I think in future is possible implement the share by name option
E.g slcli image share 123456 --name testname

2023-03-10 22:01 UTC, caberos requested changes

2023-03-10 22:01 UTC, caberos commented on tests/CLI/modules/image_tests.py
> +    def test_share_without_id(self):
add a assert to error message

2023-03-16 13:37 UTC, allmightyspiff approved these changes

2023-03-16 13:47 UTC, caberos approved these changes
LGTM

2023-03-17 13:40 UTC, merged