Added new command - slcli cdn delete
softlayer/softlayer-python pull request #1896
Opened 2023-03-30 15:04 UTC by edsonarios

Issue link: #1895
```
softlayer-python/ (issue1895) $ slcli cdn delete 214030593705200
Cdn with uniqueId: 214030593705200 was deleted.
```

2023-03-31 14:11 UTC, caberos requested changes

2023-03-31 14:11 UTC, caberos commented on SoftLayer/CLI/cdn/delete.py
> +    # cdn_mapping = manager.get_cdn(unique_id)
remove this comment line

2023-04-04 15:44 UTC, BrianSantivanez approved these changes
Looks good to me

2023-04-04 19:14 UTC, caberos approved these changes
LGTM

2023-04-04 20:03 UTC, allmightyspiff approved these changes

2023-04-04 20:03 UTC, merged