New command: slcli order quote-delete
softlayer/softlayer-python pull request #1918
Opened 2023-04-19 19:05 UTC by caberos

[#issue1915](https://github.com/softlayer/softlayer-python/issues/1915)

![image](https://user-images.githubusercontent.com/22535437/233175258-8846b6f5-41e7-4f2c-b2d2-edef05ab5c85.png)

2023-04-20 13:15 UTC, edsonarios commented on SoftLayer/CLI/order/quote_delete.py
> +    """View a quote"""
Maybe should be "Delete the quote of an order"

2023-05-01 13:21 UTC, allmightyspiff commented
![image](https://user-images.githubusercontent.com/7408017/235457328-0279e6a5-993f-4f20-8b94-c730e436607e.png)

2023-05-01 13:24 UTC, allmightyspiff requested changes
Looks good, just a slight change to use  [F strings](https://peps.python.org/pep-0498/). Thanks

2023-05-01 13:24 UTC, allmightyspiff commented on SoftLayer/CLI/order/quote_delete.py
> +        env.fout("Quote id: {} was deleted.".format(identifier))
I'd like to start using Python F strings going forward, as they read a little better.

```suggestion
        env.fout(f"Quote id: {identifier} was deleted.")
```

2023-05-02 18:13 UTC, ramkishor-ch commented
Hi,

I have "tested the changes".
Please find the screenshot for reference.

Screen Shot: 1
<img width="758" alt="Screenshot 2023-05-02 at 11 19 56 PM" src="https://user-images.githubusercontent.com/125332006/235749126-235a0115-0069-44b0-9353-2a4979044c83.png">

Screen Shot: 2
<img width="769" alt="Screenshot 2023-05-02 at 11 36 26 PM" src="https://user-images.githubusercontent.com/125332006/235749190-a9d447a2-f1aa-4d0a-8642-6f729d603877.png">

Screen Shot: 3
<img width="779" alt="Screenshot 2023-05-02 at 11 21 32 PM" src="https://user-images.githubusercontent.com/125332006/235749395-fb85bb29-161f-4501-8fd0-deb48325e95a.png">

Screen Shot: 4
<img width="775" alt="Screenshot 2023-05-02 at 11 23 50 PM" src="https://user-images.githubusercontent.com/125332006/235749489-251c7c5d-c6f2-491f-8b02-7dd10f78a3b0.png">

Thanks,
Ramkishor Chaladi.

2023-05-02 18:19 UTC, ramkishor-ch approved these changes
Hi
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

2023-05-02 21:01 UTC, allmightyspiff approved these changes

2023-05-02 21:01 UTC, merged