add a new command on order items-cancelation
softlayer/softlayer-python pull request #1929
Opened 2023-05-02 15:41 UTC by caberos

[#issue1927](https://github.com/softlayer/softlayer-python/issues/1927)

![image](https://user-images.githubusercontent.com/22535437/235716009-bc94ec30-f45e-42e5-8e60-0809baa4a18e.png)

2023-05-03 00:22 UTC, edsonarios commented
Screenshots of the test result
![image](https://user-images.githubusercontent.com/43519769/235812091-b99415f4-f649-4cd5-874d-ea831b97eb70.png)

2023-05-03 00:26 UTC, edsonarios approved these changes
Looks good to me

2023-05-03 19:13 UTC, edsonarios commented on SoftLayer/CLI/order/cancelation.py
> +    """List all active quotes on an account"""
Maybe is needed to update this description

2023-05-05 13:27 UTC, allmightyspiff commented on SoftLayer/managers/ordering.py
> +        mask = 'mask[id,itemCount,modifyDate,createDate,ticketId,' \
Have the mask be only the columns we need to display, which will make the API command much faster.

2023-05-05 13:35 UTC, allmightyspiff commented on SoftLayer/managers/ordering.py
> +        return self.client.call('SoftLayer_Billing_Item_Cancellation_Request', 'getAllCancellationRequests', mask=mask)
Add a limit of 50 here, for this method the default is only 25 which I don't think is quite enough. Showing the last 50 cancellations should be good though.

2023-05-08 15:25 UTC, allmightyspiff requested changes

2023-05-09 12:28 UTC, ramkishor-ch commented
Hi,

I have "tested the changes".
Please find the screenshot for reference.

Screen Shot: 1
<img width="632" alt="Screenshot 2023-05-09 at 4 20 23 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/2ceb5fcd-b65e-4bf3-a4f2-f504cba38f10">

Thanks,
Ramkishor Chaladi.

2023-05-09 12:29 UTC, ramkishor-ch approved these changes
Hi,
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

2023-05-09 21:01 UTC, allmightyspiff approved these changes

2023-05-09 21:01 UTC, merged