New Command: `slcli security`
softlayer/softlayer-python pull request #1951
Opened 2023-05-16 14:16 UTC by BrianSantivanez

Issue: https://github.com/softlayer/softlayer-python/issues/1942
Observations: `sshkeys` and `ssl` features were merged into `security` feature, and core test were updated to work with commands names that start with other command names (securitygroup and security), before this upgrade if exists a command that starts with other command name this test fails 
```
slcli security -h
Usage: slcli security [OPTIONS] COMMAND [ARGS] ...

        SSH Keys and SSL Certificates.

┌────┬────────┬─────────────────────────────┐
│ -h │ --help │ Show this message and exit. │
└────┴────────┴─────────────────────────────┘

Commands:
  cert-add       Add and upload SSL certificate details.
  cert-download  Download SSL certificate and key file.
  cert-edit      Edit SSL certificate.
  cert-list      List SSL certificates.
  cert-remove    Remove SSL certificate.
  sshkey-add     Add a new SSH key.
  sshkey-edit    Edits an SSH key.
  sshkey-list    List SSH keys.
  sshkey-print   Prints out an SSH key to the screen.
  sshkey-remove  Permanently removes an SSH key.
```

2023-05-17 18:24 UTC, ramkishor-ch commented
Hi @allmightyspiff,
When I executed the **slcli sshkey** and **slcli ssl** commands that were generated an **ERROR**,
not working as expected

Hi @BrianSantivanez,
After checkout of BrianSantivanez-issue1942 changes into local system.
When I tried to run With Fix of #1942
./slcli ssl --help
Usage: slcli [OPTIONS] COMMAND [ARGS] ...
Try 'slcli --help' for help.
**Error**: No such command 'ssl'.

 ./slcli sshkey --help
Usage: slcli [OPTIONS] COMMAND [ARGS] ...
Try 'slcli --help' for help.
**Error**: No such command 'sshkey'.

Can you please fix the issue.

Thanks,
Ramkishor Chaladi.

2023-05-17 20:43 UTC, BrianSantivanez commented
> 

Hi @ramkishor-ch, the errors you mentioned are expected because `slcli sshkey` and `slcli ssl` were removed and all their commands were added in `slcli security` 

![image](https://github.com/softlayer/softlayer-python/assets/78806346/ae33d97a-4c96-431c-963e-8285924f586a)

If you want to run some `sshkey` or `ssl` command you have to do from `slcli security`

![image](https://github.com/softlayer/softlayer-python/assets/78806346/c4014980-fcf9-4589-9cf0-de95aecfd2cd)

2023-05-18 06:33 UTC, ramkishor-ch commented
Hi @BrianSantivanez,

I already knew that **slcli sshkey** and **slcli ssl** commands were moved under **slcli security**, but I have already discussed the same doubt on yesterday with @allmightyspiff.

@allmightyspiff was told that **"** make sure still old commands: **slcli sshkey** and **slcli ssl** should work though that were added into **slcli security** because anyone using the **slcli sshkey** and **slcli ssl** still be able to use the old commands so it **doesn't break** their **automation** and if the commands **DON'T exist**, thats a **problem** that **needs** to be **fixed** **"**.

Can you please fix the issue.

Thanks,
Ramkishor Chaladi.

2023-05-18 12:23 UTC, allmightyspiff commented
@BrianSantivanez There should still be an alias for `slcli sshkey` and `slcli ssl` for users who have these commands in some automation. I don't want to break existing features.

Moving the commands into a single `security` command is good, but we should add alias routes for them as well. Thanks

Basically just add these to `routes.py` courtesy of Ramkishor
```python
    ('sshkey', 'SoftLayer.CLI.sshkey'),
    ('sshkey:add', 'SoftLayer.CLI.security.sshkey_add:cli'),
    ('sshkey:remove', 'SoftLayer.CLI.security.sshkey_remove:cli'),
    ('sshkey:edit', 'SoftLayer.CLI.security.sshkey_edit:cli'),
    ('sshkey:list', 'SoftLayer.CLI.security.sshkey_list:cli'),
    ('sshkey:print', 'SoftLayer.CLI.security.sshkey_print:cli'),
    ('ssl', 'SoftLayer.CLI.ssl'),
    ('ssl:add', 'SoftLayer.CLI.security.cert_add:cli'),
    ('ssl:download', 'SoftLayer.CLI.security.cert_download:cli'),
    ('ssl:edit', 'SoftLayer.CLI.security.cert_edit:cli'),
    ('ssl:list', 'SoftLayer.CLI.security.cert_list:cli'),
    ('ssl:remove', 'SoftLayer.CLI.security.cert_remove:cli'),
```

2023-05-18 12:27 UTC, allmightyspiff requested changes

2023-05-18 12:27 UTC, allmightyspiff commented on SoftLayer/CLI/environment.py
> +                if ':' not in command[offset:]:
Why was this added?

2023-05-18 12:27 UTC, allmightyspiff commented on SoftLayer/CLI/routes.py
> -    ('ssl:remove', 'SoftLayer.CLI.ssl.remove:cli'),
Add these back in, but pointed at the `SoftLayer.CLI.security.<command>` modules so that users can still call these commands. Thanks

2023-05-19 11:14 UTC, ramkishor-ch commented
Hi,

I have "tested the changes".
Please find the screenshots for reference.

Screen Shot: 1
<img width="933" alt="Screenshot 2023-05-19 at 4 30 01 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/79a69f29-1d16-4947-a607-59e729897ac3">


Screen Shot: 2
<img width="720" alt="Screenshot 2023-05-19 at 4 31 28 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/817cf63e-741c-4296-beb3-c357137b3494">


Screen Shot: 3
<img width="725" alt="Screenshot 2023-05-19 at 4 32 18 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/da63b70e-e1e9-4bb8-a680-8d88ad6d3960">


Screen Shot: 4
<img width="662" alt="Screenshot 2023-05-19 at 4 33 05 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/2d23555f-958e-46a2-8ef7-2641a9329f06">


Screen Shot: 5
<img width="718" alt="Screenshot 2023-05-19 at 4 33 41 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/2fe6e2e1-8181-45f4-8cfb-6bfa5d1c53fd">


Screen Shot: 6
<img width="640" alt="Screenshot 2023-05-19 at 4 34 07 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/d0513e99-2a6e-4092-88ee-18ff183db4ae">



Thanks,
Ramkishor Chaladi.

2023-05-19 11:16 UTC, ramkishor-ch approved these changes
Hi,
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

2023-05-22 18:31 UTC, allmightyspiff approved these changes

2023-05-22 18:31 UTC, merged