Added "Deletion Scheduled" to bandwidth pools and pool-details
softlayer/softlayer-python pull request #2005
Opened 2023-06-29 00:22 UTC by edsonarios

Issue: #2002
´´´
softlayer-python/ (issue2002) $ slcli bandwidth pools
                                                            Bandwidth Pools
┌─────────┬──────────────────────┬─────────────────┬─────────┬────────────┬───────────────┬─────────────────┬──────┬──────────────────┐
│ Id      │ Name                 │ Region          │ Devices │ Allocation │ Current Usage │ Projected Usage │ Cost │ Deletion         │
├─────────┼──────────────────────┼─────────────────┼─────────┼────────────┼───────────────┼─────────────────┼──────┼──────────────────┤
│ 12928   │ Test_8_Region        │ IND             │ 0       │ 0 GB       │ 0 GB          │ 0 GB            │ $0.0 │ 2023-07-03 22:59 │
└─────────┴──────────────────────┴─────────────────┴─────────┴────────────┴───────────────┴─────────────────┴──────┴──────────────────┘
´´´
´´´
softlayer-python/ (issue2002) $ slcli bandwidth pools-detail 12928
┌──────────────────┬──────────────────┐
│             name │ value            │
├──────────────────┼──────────────────┤
│               Id │ 12928            │
│             Name │ Test_8_Region    │
│      Create Date │ 2023-06-02 00:00 │
│         End Date │ 2023-07-03 22:59 │
│    Current Usage │ None GB          │
│ Projected  Usage │ 0 GB             │
│  Inbound   Usage │ 0 GB             │
│         hardware │ Not Found        │
│    virtualGuests │ Not Found        │
│        Netscaler │ Not Found        │
└──────────────────┴──────────────────┘
´´´

2023-06-29 16:16 UTC, caberos approved these changes
LGTM

2023-06-30 12:23 UTC, ramkishor-ch commented
HI,

I have tested the changes,
Please find the screen shots for reference.

Screen Shot:
<img width="974" alt="Screenshot 2023-06-30 at 5 51 03 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/3329593d-a334-4dda-a10d-b4866a1b82c4">

Thanks,
Ramkishor Chaladi.

2023-06-30 12:24 UTC, ramkishor-ch approved these changes

2023-07-03 13:13 UTC, allmightyspiff requested changes

2023-07-03 13:13 UTC, allmightyspiff commented on SoftLayer/CLI/bandwidth/pools.py
> +        deletion = utils.clean_time(item.get('endDate'))
Add a blank value if this is empty

2023-07-06 02:43 UTC, allmightyspiff commented
This pull request will be handled in https://github.com/softlayer/softlayer-python/pull/2006

2023-07-06 02:43 UTC, closed without merging