Fixed Description and some features are missing in slcli block snapshot-set-notification, slcli block subnets-assign, slcli block subnets-list, slcli block subnets-remove
softlayer/softlayer-python pull request #2047
Opened 2023-07-18 14:57 UTC by ramkishor-ch

Hi @allmightyspiff,

Fixes: #2014

**Title:**
Fixed Description and some features are missing in slcli block snapshot-set-notification, slcli block subnets-assign, slcli block subnets-list, slcli block subnets-remove

**Description:**
I have added Example text in the commands like...
1.
a. The **set_volume_snapshot_notification(volume_id, enable)** API is returning empty value, because of that confirmation message "Snapshots space usage threshold warning notification has bee set to %s for volume %s" is not getting displayed, so I have removed the ```if status:``` line of code.
b. The problem: ./slcli block snapshot-set-notification will be fixed in this issue: https://github.com/softlayer/softlayer-python/issues/2046.

Expected:
```
./slcli block snapshot-set-notification --help
Usage: slcli block snapshot-set-notification [OPTIONS] VOLUME_ID

        Enables/Disables snapshot space usage threshold warning for a given volume.

┌────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│    │ volume_id │                                                                                                                            │
│    │ --enable/--disable │ Enable/Disable snapshot notification. Use `slcli block snapshot-set-notification volumeId --enable` to enable.  [required] │
│ -h │ --help    │ Show this message and exit.                                                                                                │
└────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
2. Added Example message in ./slcli block subnets-assign --help
3. Added Example message in ./slcli block subnets-list --help
4. Added Example message in ./slcli block subnets-remove --help

Please find the screenshots for reference.

Screen Shots:
1, 2, 3, 4:
<img width="879" alt="Screenshot 2023-07-18 at 8 23 54 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/e640b08e-37b7-481a-9836-8963824af8df">

Thanks,
Ramkishor Chaladi.

2023-07-19 00:58 UTC, allmightyspiff requested changes
On the documentation changes you made, keep the description first, and use 2 :: to mark the Example:: line

2023-07-19 00:58 UTC, allmightyspiff commented on SoftLayer/CLI/block/subnets/assign.py
> +    Assign block storage subnets to the given host id.
The short description should be first.
EXAMPLE should have 2 colons (`::`), this is a special notation for the documentation ( https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks)
```suggestion
    """Assign block storage subnets to the given host id.
    
    EXAMPLE::

                slcli block subnets-assign 111111 --subnet-id 222222
                slcli block subnets-assign 111111 --subnet-id 222222 --subnet-id 333333
                ACCESS_ID is the host_id obtained by: softlayer slcli block access-list <volume_id>
```

2023-07-19 08:28 UTC, ramkishor-ch commented
Hi @allmightyspiff,

As suggested, I updated the changes, please review it.

Screen Shot:
<img width="708" alt="Screenshot 2023-07-19 at 1 55 40 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/74099f04-08ee-4876-8bc7-26173db98edd">

Thanks,
Ramkishor Chaladi.

2023-07-24 21:02 UTC, allmightyspiff approved these changes

2023-07-24 21:02 UTC, merged