--force option for slcli firewall add, firewall cancel command - issue #2032
softlayer/softlayer-python pull request #2052
Opened 2023-07-21 22:16 UTC by JayasilanJibm

Hi,

Fixes: #2032 

Please review this PR. 

Added force option for both slcli firewall add and cancel command.

Thanks,
Jayasilan

2023-07-24 20:58 UTC, allmightyspiff requested changes
Minor formatting changes, mostly just use `Example::` (with 2 :: at the end). Its a special syntax for the automatic documentation generator we use.

2023-07-24 20:58 UTC, allmightyspiff commented on SoftLayer/CLI/file/list.py
> +            """
```suggestion
    """List file storage.

    Example::
            slcli file volume-list -d dal10 --storage-type endurance --sortby capacity_gb
    """
```

2023-07-24 20:58 UTC, allmightyspiff commented on SoftLayer/CLI/file/modify.py
> +    Examples:
```suggestion
    Example::
```

2023-07-24 20:58 UTC, allmightyspiff commented on SoftLayer/CLI/file/options.py
> +    Examples:
```suggestion
    Example::
```

2023-07-27 10:35 UTC, ramkishor-ch commented
Hi,

Code looks good.

<img width="677" alt="Screenshot 2023-07-27 at 4 03 29 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/4be472b0-2a2d-45e4-979e-04e21318b688">

Thanks,
Ramkishor Chaladi.

2023-07-27 10:35 UTC, ramkishor-ch approved these changes

2023-07-27 20:47 UTC, allmightyspiff approved these changes

2023-07-27 20:47 UTC, merged