Feature added in slcli block snapshot-cancel, Text updated in slcli block snapshot-enable
softlayer/softlayer-python pull request #2059
Opened 2023-08-02 10:51 UTC by ramkishor-ch

Hi @allmightyspiff,

Fixes: #2013 

**Title:**
Text update and option needs to added in slcli block snapshot-cancel, ./slcli block snapshot-enable

**Description:**
1. I have added feature called force in ./slcli block snapshot-cancel --help 
2. I have updated the text for --minute, --hour, --day-of-week in ./slcli block snapshot-enable --help.

Please find the screen shot.

Please review it.

**Screen Shot:**
<img width="758" alt="Screenshot 2023-08-02 at 4 16 16 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/4439feab-c229-4db2-84cd-5f08181ecfee">

Thanks,
Ramkishor Chaladi.

2023-08-03 20:47 UTC, allmightyspiff requested changes
Looks good, just make the help message one line since the length is <120 characters.

2023-08-03 20:47 UTC, allmightyspiff commented on SoftLayer/CLI/block/snapshot/enable.py
> +              'integer between 0 to 59.',
```suggestion
              help='Minute of the hour when snapshots should be taken, integer between 0 to 59.',
```
for this project the line length is 120 characters, so I prefer to keep things on one line if possible.

2023-08-03 20:47 UTC, allmightyspiff commented on SoftLayer/CLI/block/snapshot/enable.py
> +              'integer between 0 to 23.',
```suggestion
              help='Hour of the day when snapshots should be taken, integer between 0 to 23.',
```

2023-08-03 20:47 UTC, allmightyspiff commented on SoftLayer/CLI/block/snapshot/enable.py
> +              'integer between 0 to 6',
```suggestion
              help='Day of the week when snapshots should be taken, integer between 0 to 6',
```

2023-08-04 11:05 UTC, ramkishor-ch commented
Hi @allmightyspiff,

As suggested, I have updated and re-tested it.

Please find the screen shot.

Screen Shot:
<img width="760" alt="Screenshot 2023-08-04 at 4 27 37 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/d540f757-0578-4529-b51e-0960882c9d0f">

Please re-review it.

Thanks,
Ramkishor Chaladi.

2023-08-08 14:30 UTC, merged