Enable all user permissions doesn't get all permissions
softlayer/softlayer-python pull request #2070
Opened 2023-08-07 18:55 UTC by ramkishor-ch

Hi @allmightyspiff,

Fixes: #1956 

**Title:**
Enable all user permissions doesn't get all permissions

**Description:**
I have hidden permissions from permission list.

I have **tested** it, please find the screen shot.

Please **review** it.

**Screen Shot 1:**
<img width="809" alt="Screenshot 2023-08-08 at 12 08 12 AM" src="https://github.com/softlayer/softlayer-python/assets/125332006/4e450876-beb7-464b-99bc-82b48d5f302c">

**Screen Shot 2:**
<img width="931" alt="Screenshot 2023-08-08 at 12 11 08 AM" src="https://github.com/softlayer/softlayer-python/assets/125332006/999a9453-849b-4cdc-9749-3099993c077b">

Thanks,
Ramkishor Chaladi.

2023-08-08 15:09 UTC, allmightyspiff requested changes

2023-08-08 15:09 UTC, allmightyspiff commented on SoftLayer/CLI/user/permissions.py
> +            table.add_row([perm['name'], perm['keyName'], assigned])
use this logic, that way we don't have empty rows in the results.
```suggestion
        if perm['keyName'] not in hide_permission_list:
            table.add_row([perm['name'], perm['keyName'], assigned])
```

Also, Add a unit test to make sure these permissions don't show up in the output.

2023-08-08 18:33 UTC, ramkishor-ch commented
Hi @allmightyspiff,

As suggested updated the code, added unit test case and re-tested it.

Please re-review it.

Please find the screen shot.

Screen Shot: 1
<img width="805" alt="Screenshot 2023-08-08 at 11 53 02 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/91afe488-fc85-49e5-9aab-0b64fc67ee0c">

Screen Shot: 2
<img width="803" alt="Screenshot 2023-08-08 at 11 54 34 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/465fb618-746f-45c7-b760-0bea4e78b6a4">

Screen Shot: 3
<img width="932" alt="Screenshot 2023-08-08 at 11 59 16 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/88c4c9ee-d631-414c-9527-2f6d7e6bf95d">

Thanks,
Ramkishor Chaladi.

2023-08-14 02:00 UTC, allmightyspiff approved these changes

2023-08-14 02:00 UTC, merged